# Generated by Django 4.2.9 on 2024-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('subtitle', models.TextField()),
                ('asrtype', models.CharField(blank=True, max_length=10)),
                ('duration', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
