# Generated by Django 4.2.7 on 2024-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttg', '0002_gesture_characters_not_found_gesture_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('subtitle', models.TextField()),
                ('asrtype', models.CharField(blank=True, max_length=10)),
                ('duration', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
