# Generated by Django 4.2.9 on 2024-01-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttg', '0003_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
